server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://web:5200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /items {
        proxy_pass http://web:5200/items;
    }

    location /health/ {
        deny all;
    }
}